config:
  jwtSecret: ${JWT_SECRET:83921jhdisahiuheas289312}
  jwtExpirationMs: ${JWT_EXPIRATION_MS:3600000}
  access_key_id: ${ACCESS_KEY_ID}
  secret_access_key: ${SECRET_ACCESS_KEY}
  github:
    client-id: ${CLIENT_ID_GITHUB}
    client-secret: ${CLIENT_SECRET_GITHUB}