name: Release Azaras
on:
  workflow_dispatch:

  workflow_call:
    inputs:
      ECR_REPOSITORY: 
        required: false
        default: $secrets.SEGREDO
        # jobs.image-tag.steps.set-image-tag.outputs.tag
        type: string
    secrets:
      ECR_REGISTRY: 
        required: true
      ECR_REPOSITORY: 
        required: true
      SEGREDO: 
        required: true


jobs:
  cancel-previous:
      name: Cancel Previous Runs
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.0
          with:
            access_token: ${{ github.token }}
  gen-tag:
    name: Gen tag
    outputs:
      image: ${{ steps.set-image-tag.outputs.image }}
      tag: ${{ steps.set-image-tag.outputs.tag }}
      registry: ${{ steps.set-image-tag.outputs.registry }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Tagged image setup
      id: set-image-tag
      env:
        ECR_REGISTRY: ${{ secrets.SEGREDO }}
        ECR_REPOSITORY: superrepo
      run: |
        # set image tag
        var1=$ECR_REGISTRY
        var2=$ECR_REPOSITORY
        echo "::add-mask::$ECR_REGISTRY"
        REGISTRY_CRYPTO=$(gpg --symmetric --batch --passphrase "SECRET" --output - <(echo $ECR_REGISTRY) | base64 -w0)
        echo "::add-mask::$ECR_REPOSITORY"
        echo "::set-output name=registry::$REGISTRY_CRYPTO"
        echo "::set-output name=tag::$REGISTRY_CRYPTO/$var2:${GITHUB_REF##*/}"
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}"
    
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: gen-tag

    steps:
    - name: Out
      id: outtage
      run: |
        encrypted_value=
        decrypted_value=$(gpg --decrypt --quiet --batch --passphrase "SECRET" --output - <(echo "${{ needs.gen-tag.outputs.registry }}" | base64 --decode))
        echo "run1 $decrypted_value"
        echo "espec1 set image deployment/api api=${{ needs.gen-tag.outputs.tag }} -n app-app"
        echo "espec2 set image deployment/api api=${{ needs.gen-tag.outputs.image }} -n app-app"
        echo "espec3 ${{ needs.gen-tag.outputs.image }}
        echo "espec4 set image deployment/api api=$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/} -n app-app"
        echo "espec5 Segredo: ${{ secrets.SEGREDO }}"
    
