name: Release Azaras
on:
  workflow_dispatch:

jobs:
  cancel-previous:
      name: Cancel Previous Runs
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.0
          with:
            access_token: ${{ github.token }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Tagged image setup
      id: set-image-tag
      env:
        ECR_REGISTRY: workRoll
        ECR_REPOSITORY: superrepo
      run: |
        # set image tag
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}"
    
    - name: Out
      id: outtage
      run: echo "set image deployment/api-04 api-04=${{ steps.set-image-tag.outputs.image }} -n app-app"
    