on: 
  workflow_dispatch:

name: Echo
jobs:

  log:
    name: Log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: run_run
        name: First Run
        run: |
          echo ref: ${{ github.ref }}
          echo ref_name: ${{ github.ref_name }}
          echo base_ref: ${{ github.base_ref }}
          echo head_ref: ${{ github.head_ref }}
          # if [ $TAG = "V1" ]; then 
          #     echo "Isso" 
          # else 
          #     echo "Não"
          # fi
