on: 
  workflow_dispatch:

name: Echo
jobs:

  log:
    name: Log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: run_run
        name: First Run
        run: |
          echo ref: ${{ github.ref }}
          echo ref_name: ${{ github.ref_name }}
          echo base_ref: ${{ github.base_ref }}
          echo head_ref: ${{ github.head_ref }}
          if [ ${{ github.ref_name }} = "development" ]; then 
              echo "image=$(echo ecr/image-dev:${{github.ref_name}})" >> $GITHUB_OUTPUT
          else 
              echo "image=$(echo ecr/image:${{github.ref_name}})" >> $GITHUB_OUTPUT
          fi

      - id: echo_i
        name: Echo output
        run: |
          echo ${{ steps.run_run.outputs.image }}