name: Kustomize Release
on:
  release:
    types:
      - prereleased

jobs:
  cancel-previous:
      name: Cancel Previous Runs
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.0
          with:
            access_token: ${{ github.token }}

  UpdateTag :
    name: Update deployment tag version
    runs-on: ubuntu-latest
    env:
      ECR_REGISTRY: repo_vez
      ECR_REPOSITORY: image-hq-ha
    steps :

      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v2

      - name : Update development
        run : |
          cd k8s/overlays/development/
          kustomize edit set image $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}
      - name : Update production
        run : |
          cd k8s/overlays/production/
          kustomize edit set image $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_REF##*/}
      
      - name : Commit
        run : |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Set image tag to `${GITHUB_REF##*/}`"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master