name: Restart APIs
on: 
  workflow_dispatch:
    inputs:
      development:
        description: 'Ambiente de desenvolvimento'
        required: false 
        type: boolean 
      homologation:
        description: 'Ambiente de homologação'
        required: false 
        type: boolean 
      production:
        description: 'Ambiente de produção'
        required: false 
        type: boolean 

jobs:
  restart-production:
    name: Restart Production
    runs-on: ubuntu-latest
    env: 
      api_selected: ${{github.event.inputs.production}}
    steps:
      - name: Restart Production
        id: restart-production-api
        if: ${{env.api_selected}}
        run: | 
          echo "restart production service"
          

  restart-homologation:
    name: Restart Homologation
    runs-on: ubuntu-latest
    env: 
      api_selected: ${{github.event.inputs.homologation}}
    steps:
      - name: Restart Homologation
        id: restart-homologation-api
        if: ${{env.api_selected}}
        run: | 
          echo "restart Homologation service"

  restart-development:
    name: Restart Development
    runs-on: ubuntu-latest
    env: 
      api_selected:  ${{github.event.inputs.development}}
    steps:
      - name: Restart Development
        id: restart-homologation-api
        if: ${{env.api_selected}}
        run: | 
          echo "restart Development service"
