name: Restart APIs
on: 
  workflow_dispatch:
    inputs:
      development:
        description: 'Ambiente de desenvolvimento'
        required: false 
        type: boolean 
      homologation:
        description: 'Ambiente de homologação'
        required: false 
        type: boolean 
      production:
        description: 'Ambiente de produção'
        required: false 
        type: boolean 

jobs:
  restart-production:
    name: Restart Production
    runs-on: ubuntu-latest
    if: github.event.inputs.production == 'true'
    steps:
      - name: Restart Production
        id: restart-production-api
        if: env.api_selected
        run: | 
          echo "restart production service"
          

  restart-homologation:
    name: Restart Homologation
    runs-on: ubuntu-latest
    if: github.event.inputs.homologation == 'true'
    steps:
      - name: Restart Homologation
        id: restart-homologation-api
        if: ${{env.api_selected}}
        run: | 
          echo "restart Homologation service"
          
      - name: Restart Homologation
        id: step2-homologation-api
        if: ${{env.api_selected}}
        run: | 
          echo "step 2 Homologation service"

  restart-development:
    name: Restart Development
    runs-on: ubuntu-latest
    env: 
      api_selected:  ${{github.event.inputs.development}}
    steps:
      - name: Restart Development
        id: restart-homologation-api
        if: env.api_selected == 'true'
        run: | 
          echo "restart Development service"
