on: 
  push:
  release:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean 
      image:
        description: 'image repo'
        required: false
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: build
        id: build
        env:
          TAGS: ${{ github.event.inputs.tags }}
          IMAGE_NAME: ${{ github.event.inputs.image }}
          IMAGETAG: LATEST
        run: |
          echo "Tags: $TAGS"
          echo "image repo: $IMAGE_NAME"
          echo ${GITHUB_EVENT_NAME} GITHUB_EVENT_NAME
          echo ${{ github.event_name }}
          echo "::save-state name=image::$IMAGETAG"
      - name: test
        run: |
          echo "{{ steps.build.outputs.image }}"
          echo ${{ steps.build.outputs.image }}
